name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ["test/local-test", "test/github-test"]
    steps:
    - uses: actions/checkout@v4
    - uses: volta-cli/action@v3
    - name: Setup the root project (only for local-test)
      run: |
        npm ci
        npm run build
      working-directory: .
      if: ${{ matrix.directory == 'test/local-test' }}
    - name: Install dependencies in ${{ matrix.directory }}
      run: npm ci
      working-directory: ${{ matrix.directory }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for github-test
    - name: Build ${{ matrix.directory }}
      run: npm run build
      working-directory: ${{ matrix.directory }}
